name: Build and Release Monitora

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: '输入你要发版的版本号 (例如 v1.0.1)'
        required: true
        default: 'latest-build'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Prepare Release Package
        run: |
          mkdir release_package
          cp -r dist release_package/
          cp package.json release_package/
          cp package-lock.json release_package/
          cd release_package
          zip -r ../monitora-release.zip ./*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          # 如果是手动触发就用输入框里的字，如果是推代码触发就用原有的 Tag
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          name: Release ${{ github.event.inputs.version || github.ref_name }}
          files: monitora-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
